
services:
  # Веб-сервер
  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  # Node.js (для фронтенда, если нужно)
  node:
    image: node:18
    container_name: laravel_node
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    command: npm run dev --host=0.0.0.0
    ports:
      - "3000:3000"

  # PHP приложение (Laravel)
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel_app
    volumes:
      - ./:/var/www/html
    depends_on:
      - postgres
      - redis  # Убедись, что приложение зависит от Redis

  # База данных
  postgres:
    image: postgres:15
    container_name: laravel_postgres
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Redis сервис
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"  # Порт Redis
    networks:
      - laravel_network

volumes:
  postgres_data:

networks:
  laravel_network:
    driver: bridge
